{"Subproblems": [{"Testcases": [{"status": 10, "Time": 0, "Memory": 0, "Input": "0\n0", "Answer": "0", "Output": "", "Description": "[Errno 2] No such file or directory: '/var/local/lib/isolate/1/box/meta'Fatal error when running."}, {"status": 7, "Time": 0, "Memory": 0, "Input": "7\n8", "Answer": "15", "Output": "", "Description": "/usr/bin/python3.7: can't open file 'P1_': [Errno 2] No such file or directory\n"}, {"status": 7, "Time": 0, "Memory": 0, "Input": "4\n3", "Answer": "7", "Output": "", "Description": "/usr/bin/python3.7: can't open file 'P1_': [Errno 2] No such file or directory\n"}], "Debugger": true, "Score": 50, "GetScore": 0}, {"Testcases": [{"status": 7, "Time": 0, "Memory": 0, "Input": "0\n6", "Answer": "6", "Output": "", "Description": "/usr/bin/python3.7: can't open file 'P1_': [Errno 2] No such file or directory\n"}, {"status": 7, "Time": 0, "Memory": 0, "Input": "7\n2", "Answer": "9", "Output": "", "Description": "/usr/bin/python3.7: can't open file 'P1_': [Errno 2] No such file or directory\n"}, {"status": 7, "Time": 0, "Memory": 0, "Input": "4\n2", "Answer": "6", "Output": "", "Description": "/usr/bin/python3.7: can't open file 'P1_': [Errno 2] No such file or directory\n"}], "Debugger": false, "Score": 50, "GetScore": 0}], "status": 11, "score": 0}