{"Subproblems": [{"Testcases": [{"status": 7, "Time": 0, "Memory": 0, "Input": "5\n7", "Answer": "210", "Output": "", "Description": "/usr/bin/python3.7: can't open file 'P3_': [Errno 2] No such file or directory\n"}, {"status": 7, "Time": 0, "Memory": 0, "Input": "10\n10", "Answer": "48620", "Output": "", "Description": "/usr/bin/python3.7: can't open file 'P3_': [Errno 2] No such file or directory\n"}, {"status": 7, "Time": 0, "Memory": 0, "Input": "1\n1", "Answer": "1", "Output": "", "Description": "/usr/bin/python3.7: can't open file 'P3_': [Errno 2] No such file or directory\n"}, {"status": 7, "Time": 0, "Memory": 0, "Input": "15\n37", "Answer": "845649741", "Output": "", "Description": "/usr/bin/python3.7: can't open file 'P3_': [Errno 2] No such file or directory\n"}, {"status": 7, "Time": 0, "Memory": 0, "Input": "1\n7", "Answer": "1", "Output": "", "Description": "/usr/bin/python3.7: can't open file 'P3_': [Errno 2] No such file or directory\n"}, {"status": 7, "Time": 0, "Memory": 0, "Input": "7\n2", "Answer": "7", "Output": "", "Description": "/usr/bin/python3.7: can't open file 'P3_': [Errno 2] No such file or directory\n"}, {"status": 7, "Time": 0, "Memory": 0, "Input": "4\n32", "Answer": "5984", "Output": "", "Description": "/usr/bin/python3.7: can't open file 'P3_': [Errno 2] No such file or directory\n"}, {"status": 7, "Time": 0, "Memory": 0, "Input": "1000\n1000", "Answer": "965601742", "Output": "", "Description": "/usr/bin/python3.7: can't open file 'P3_': [Errno 2] No such file or directory\n"}], "Debugger": true, "Score": 50, "GetScore": 0}, {"Testcases": [{"status": 7, "Time": 0, "Memory": 0, "Input": "50\n50", "Answer": "267422234", "Output": "", "Description": "/usr/bin/python3.7: can't open file 'P3_': [Errno 2] No such file or directory\n"}, {"status": 7, "Time": 0, "Memory": 0, "Input": "51\n28", "Answer": "823497870", "Output": "", "Description": "/usr/bin/python3.7: can't open file 'P3_': [Errno 2] No such file or directory\n"}, {"status": 7, "Time": 0, "Memory": 0, "Input": "93\n46", "Answer": "848374726", "Output": "", "Description": "/usr/bin/python3.7: can't open file 'P3_': [Errno 2] No such file or directory\n"}, {"status": 7, "Time": 0, "Memory": 0, "Input": "28\n23", "Answer": "896200283", "Output": "", "Description": "/usr/bin/python3.7: can't open file 'P3_': [Errno 2] No such file or directory\n"}], "Debugger": false, "Score": 50, "GetScore": 0}], "status": 11, "score": 0}